In [1]:
#pip install pandas
import pandas as pd

In [2]:
data = {
        'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Paris', 'London']
}

In [3]:
print(data)

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['New York', 'Paris', 'London']}

In [4]:
df = pd.DataFrame(data)

In [5]:
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London

In [6]:
import numpy as np

In [7]:
data = np.array([
        [1, 'Alice', 30],
        [2, 'Bob', 25],
        [3, 'Charlie', 35]
])

In [11]:
df = pd.DataFrame(data)
print(df)

   0        1   2
0  1    Alice  30
1  2      Bob  25
2  3  Charlie  35

In [12]:
df = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])
print(df)

  ID     Name Age
0  1    Alice  30
1  2      Bob  25
2  3  Charlie  35

In [21]:
df = pd.read_csv("C:/Users/USER/Desktop/Data/국영수.csv", header=0, encoding='cp949')

In [22]:
df

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [23]:
df_h = pd.read_csv("C:/Users/USER/Desktop/Data/국영수.csv", header=None, encoding='cp949')

In [24]:
df_h

    0   1   2   3
0  국어  영어  수학  체육
1  50  88  21   상
2  41  87  54   중
3  85  65  84   상
4  61  85  13   중
5  54  41  21   하
6  84  47  87   하
7  77  98  65   상
8  87  58  54   중
9  54  22  78   히

In [25]:
df.shape

(9, 4)

In [26]:
df.columns

Index(['국어', '영어', '수학', '체육'], dtype='object')

In [27]:
df.dtypes

국어     int64
영어     int64
수학     int64
체육    object
dtype: object

In [28]:
df.describe()

              국어         영어         수학
count   9.000000   9.000000   9.000000
mean   65.888889  65.666667  53.000000
std    17.467430  25.729361  28.583212
min    41.000000  22.000000  13.000000
25%    54.000000  47.000000  21.000000
50%    61.000000  65.000000  54.000000
75%    84.000000  87.000000  78.000000
max    87.000000  98.000000  87.000000

In [32]:
df.head()

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하

In [33]:
df.tail(1)

   국어  영어  수학 체육
8  54  22  78  히

In [34]:
df.isnull().sum()

국어    0
영어    0
수학    0
체육    0
dtype: int64

In [36]:
df['체육'].value_counts()

체육
상    3
중    3
하    2
히    1
Name: count, dtype: int64

In [37]:
df['체육'].unique()

array(['상', '중', '하', '히'], dtype=object)

In [41]:
df['체육'].nunique()

4

In [43]:
df['체육']

0    상
1    중
2    상
3    중
4    하
5    하
6    상
7    중
8    히
Name: 체육, dtype: object

In [44]:
df['합계'] = df['국어'] + df['영어'] + df['수학']

In [45]:
df

   국어  영어  수학 체육   합계
0  50  88  21  상  159
1  41  87  54  중  182
2  85  65  84  상  234
3  61  85  13  중  159
4  54  41  21  하  116
5  84  47  87  하  218
6  77  98  65  상  240
7  87  58  54  중  199
8  54  22  78  히  154

In [48]:
columns = ['국어', '영어', '수학']
selected_columns = df[columns]
selected_columns

   국어  영어  수학
0  50  88  21
1  41  87  54
2  85  65  84
3  61  85  13
4  54  41  21
5  84  47  87
6  77  98  65
7  87  58  54
8  54  22  78

In [49]:
df.loc[:, '국어']

0    50
1    41
2    85
3    61
4    54
5    84
6    77
7    87
8    54
Name: 국어, dtype: int64

In [51]:
selected_columns1 = df.loc[:, columns]
selected_columns1

   국어  영어  수학
0  50  88  21
1  41  87  54
2  85  65  84
3  61  85  13
4  54  41  21
5  84  47  87
6  77  98  65
7  87  58  54
8  54  22  78

In [52]:
df = df.drop(['체육'], axis=1) #axis = 0(행 삭제), 1(열 삭제)

In [54]:
df

   국어  영어  수학   합계
0  50  88  21  159
1  41  87  54  182
2  85  65  84  234
3  61  85  13  159
4  54  41  21  116
5  84  47  87  218
6  77  98  65  240
7  87  58  54  199
8  54  22  78  154

In [55]:
data = {
        'A': [1, 2, 3, 4],
        'B': [4.1, 3.5, 2.1, 5.7],
        'C': ['one', 'two', 'three', 'four']
}
df = pd.DataFrame(data)

In [75]:
df['A'] = df['A'].astype(float)
df['B'] = df['B'].astype(int)
df['A'] = df['A'].astype('str')
df['C'] = df['C'].astype('category')

In [60]:
df['C'].dtype

CategoricalDtype(categories=['four', 'one', 'three', 'two'], ordered=False, categories_dtype=object)

In [63]:
df['C']

0      one
1      two
2    three
3     four
Name: C, dtype: category
Categories (4, object): ['four', 'one', 'three', 'two']

In [76]:
df['A'] = df['A'].astype('str')

In [65]:
df['A']

0    1.0
1    2.0
2    3.0
3    4.0
Name: A, dtype: object

In [77]:
df['A'] = df['A'].astype(int)

In [78]:
df = df.rename(columns={
                        'A': '국어',
                        'B': '영어',
                        'C': '번호'
})

In [79]:
df

    국어  영어     번호
0  1.0   4    one
1  2.0   3    two
2  3.0   2  three
3  4.0   5   four

In [84]:
data = {
        'Numeric1': [1, np.nan, 3, 4],
        'Numeric2': [5, 6, np.nan, 8.2],
        'Category': ['dog', np.nan, 'cat', 'dog']
}
df = pd.DataFrame(data)

In [85]:
A = df.select_dtypes(include=['number']).columns
df[A]

   Numeric1  Numeric2
0       1.0       5.0
1       NaN       6.0
2       3.0       NaN
3       4.0       8.2

In [86]:
B = df.select_dtypes(include=['object', 'category']).columns
df[B]

  Category
0      dog
1      NaN
2      cat
3      dog

In [87]:
df[A].fillna(df[A].median())

   Numeric1  Numeric2
0       1.0       5.0
1       3.0       6.0
2       3.0       6.0
3       4.0       8.2

In [88]:
df[A].fillna(df[A].mean())

   Numeric1  Numeric2
0  1.000000       5.0
1  2.666667       6.0
2  3.000000       6.4
3  4.000000       8.2

In [90]:
df1 = pd.DataFrame({
                    'a':['a0', 'a1', 'a2', 'a3'],
                    'b':['b0', 'b1', 'b2', 'b3'],
                    'c':['c0', 'c1', 'c2', 'c3']
})
df2 = pd.DataFrame({
                    'a':['a2', 'a3', 'a4', 'a5'],
                    'b':['b2', 'b3', 'b4', 'b5'],
                    'c':['c2', 'c3', 'c4', 'c5'],
                    'd':['d2', 'd3', 'd4', 'd5']
})

In [91]:
pd.concat([df1, df2], axis=0)

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
0  a2  b2  c2   d2
1  a3  b3  c3   d3
2  a4  b4  c4   d4
3  a5  b5  c5   d5

In [93]:
pd.concat([df1, df2], axis=1)

    a   b   c   a   b   c   d
0  a0  b0  c0  a2  b2  c2  d2
1  a1  b1  c1  a3  b3  c3  d3
2  a2  b2  c2  a4  b4  c4  d4
3  a3  b3  c3  a5  b5  c5  d5

In [96]:
pd.concat([df[A], df[B]], axis=1)

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
2       3.0       NaN      cat
3       4.0       8.2      dog

In [97]:
df[(df['Numeric2'] >= 6) & (df['Numeric2'] <= 10)]

   Numeric1  Numeric2 Category
1       NaN       6.0      NaN
3       4.0       8.2      dog

In [98]:
df[(df['Numeric2'] >= 6) | (df['Numeric2'] <= 10)]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
3       4.0       8.2      dog