In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
sample = pd.read_csv("sample_1.csv")

In [4]:
sample

,연구번호,입실일자,입실시각,검사코드,검사코드NM,검사결과값(숫자),검사결과값(표시),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,진료과코드,진료과코드NM,퇴실시각,퇴실일자,환자생년월,성별코드,성별코드NM
0,1219300234,20210220,1350.0,ZF0156,"ABGA coding (Des),Artery blood",342.0,342,NaN,NaN,20210221.0,212123.0,81.0,NR,신경과,1430,20210302,193909,M,남성
1,1219300234,20210220,1350.0,ZF0016,"Bicarbonate (Qn),Artery blood",27.5,27.5,29.0,23.0,20210221.0,212123.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M,남성
2,1219300234,20210220,1350.0,ZF0155,"ABGA interpretation (Des),Artery blood",NaN,이전 동맥혈액 가스검사 판독결과가 Uncompensated respiratory a...,NaN,NaN,20210221.0,43234.0,81.0,NR,신경과,1430,20210302,193909,M,남성
3,1219300234,20210220,1350.0,BB0007,"pO2 (Qn)[EM],Artery blood",117.8,117.8,108.0,83.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M,남성
4,1219300234,20210220,1350.0,ZF0012,"O2 saturation (Qn),Artery blood",98.3,98.3,100.0,94.0,20210222.0,45628.0,81.0,PSY,정신건강의학과,1430,20210302,193909,M,남성
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,20200519,1800.0,ZF0157,"ABGA reading (Des),Artery blood",NaN,Normal ABGA,NaN,NaN,20200520.0,155439.0,66.0,END,내분비내과,1710,20200520,195307,F,여성
799996,1169043575,20200519,1800.0,BC0202,"Glucose (Qn)[POCT],Blood",299.0,299,99.0,70.0,20200520.0,155439.0,66.0,GI,소화기내과,1710,20200520,195307,F,여성
799997,1169043575,20200519,1800.0,ZF0014,"Base excess (Qn),Artery blood",-1.8,-1.8,NaN,NaN,20200520.0,155439.0,66.0,GS,일반외과,1710,20200520,195307,F,여성
799998,1169043575,20200519,1800.0,ZF0016,"Bicarbonate (Qn),Artery blood",22.9,22.9,29.0,23.0,20200520.0,155439.0,66.0,INF,감염내과,1710,20200520,195307,F,여성
799999,1169043575,20200519,1800.0,BB0074,"Potassium (Qn)[POCT],Blood",3.7,3.7,NaN,NaN,20200520.0,155439.0,66.0,NPH,신장내과,1710,20200520,195307,F,여성

In [5]:
trans1 = pd.read_csv("trans_1.csv", encoding = "cp949")

In [6]:
trans1

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,접수일자,접수시각,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,80세,2021-02-21,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",47.0,45.0,35.0,80세,2021-02-21,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464314,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",92.5,108.0,83.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464315,1169043575,2020-05-19,18:00:00,"pCO2 (Qn)[EM],Artery blood",38.1,45.0,35.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464316,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464317,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464318,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,29.0,23.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days

In [7]:
sample = sample.drop(['검사코드', '검사결과값(표시)', '성별코드NM', '진료과코드', '진료과코드NM'], axis=1)

In [8]:
sample

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,20210220,1350.0,"ABGA coding (Des),Artery blood",342.0,NaN,NaN,20210221.0,212123.0,81.0,1430,20210302,193909,M
1,1219300234,20210220,1350.0,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,20210221.0,212123.0,81.0,1430,20210302,193909,M
2,1219300234,20210220,1350.0,"ABGA interpretation (Des),Artery blood",NaN,NaN,NaN,20210221.0,43234.0,81.0,1430,20210302,193909,M
3,1219300234,20210220,1350.0,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,20210222.0,45628.0,81.0,1430,20210302,193909,M
4,1219300234,20210220,1350.0,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,20210222.0,45628.0,81.0,1430,20210302,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,20200519,1800.0,"ABGA reading (Des),Artery blood",NaN,NaN,NaN,20200520.0,155439.0,66.0,1710,20200520,195307,F
799996,1169043575,20200519,1800.0,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,20200520.0,155439.0,66.0,1710,20200520,195307,F
799997,1169043575,20200519,1800.0,"Base excess (Qn),Artery blood",-1.8,NaN,NaN,20200520.0,155439.0,66.0,1710,20200520,195307,F
799998,1169043575,20200519,1800.0,"Bicarbonate (Qn),Artery blood",22.9,29.0,23.0,20200520.0,155439.0,66.0,1710,20200520,195307,F
799999,1169043575,20200519,1800.0,"Potassium (Qn)[POCT],Blood",3.7,NaN,NaN,20200520.0,155439.0,66.0,1710,20200520,195307,F

In [9]:
sample['입실일자'] = pd.to_datetime(sample['입실일자'], format='%Y%m%d', errors='coerce')

In [10]:
sample['입실시각'] = pd.to_datetime(sample['입실시각'], format='%H%M', errors='coerce').dt.time

In [11]:
sample['접수일자'] = pd.to_datetime(sample['접수일자'], format='%Y%m%d', errors='coerce')

In [12]:
sample['퇴실일자'] = pd.to_datetime(sample['퇴실일자'], format='%Y%m%d', errors='coerce')

In [13]:
sample['퇴실시각'] = pd.to_datetime(sample['퇴실시각'], format='%H%M', errors='coerce').dt.time

In [14]:
sample

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드
0,1219300234,2021-02-20,13:50:00,"ABGA coding (Des),Artery blood",342.0,NaN,NaN,2021-02-21,212123.0,81.0,14:30:00,2021-03-02,193909,M
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,2021-02-21,212123.0,81.0,14:30:00,2021-03-02,193909,M
2,1219300234,2021-02-20,13:50:00,"ABGA interpretation (Des),Artery blood",NaN,NaN,NaN,2021-02-21,43234.0,81.0,14:30:00,2021-03-02,193909,M
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,2021-02-22,45628.0,81.0,14:30:00,2021-03-02,193909,M
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,2021-02-22,45628.0,81.0,14:30:00,2021-03-02,193909,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,2020-05-19,18:00:00,"ABGA reading (Des),Artery blood",NaN,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F
799997,1169043575,2020-05-19,18:00:00,"Base excess (Qn),Artery blood",-1.8,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,29.0,23.0,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F
799999,1169043575,2020-05-19,18:00:00,"Potassium (Qn)[POCT],Blood",3.7,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F

In [15]:
sample['환자ID']=sample['연구번호'].astype("str")

In [16]:
sample['환자ID'] = sample['환자ID'].str[0:3] + sample['환자ID'].str[5:]

In [17]:
sample

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드,환자ID
0,1219300234,2021-02-20,13:50:00,"ABGA coding (Des),Artery blood",342.0,NaN,NaN,2021-02-21,212123.0,81.0,14:30:00,2021-03-02,193909,M,12100234
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,2021-02-21,212123.0,81.0,14:30:00,2021-03-02,193909,M,12100234
2,1219300234,2021-02-20,13:50:00,"ABGA interpretation (Des),Artery blood",NaN,NaN,NaN,2021-02-21,43234.0,81.0,14:30:00,2021-03-02,193909,M,12100234
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,2021-02-22,45628.0,81.0,14:30:00,2021-03-02,193909,M,12100234
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,2021-02-22,45628.0,81.0,14:30:00,2021-03-02,193909,M,12100234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,2020-05-19,18:00:00,"ABGA reading (Des),Artery blood",NaN,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F,11643575
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F,11643575
799997,1169043575,2020-05-19,18:00:00,"Base excess (Qn),Artery blood",-1.8,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F,11643575
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,29.0,23.0,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F,11643575
799999,1169043575,2020-05-19,18:00:00,"Potassium (Qn)[POCT],Blood",3.7,NaN,NaN,2020-05-20,155439.0,66.0,17:10:00,2020-05-20,195307,F,11643575

In [22]:
sample['검사나이'] = sample['검사나이'].astype("str")

In [23]:
sample['검사나이'] = sample['검사나이'].str.rstrip(".0")

In [24]:
sample['검사나이'] = sample['검사나이']+"세"

In [25]:
sample['입원기간'] = sample['퇴실일자'] - sample['입실일자']

In [26]:
sample

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,접수일자,접수시각,검사나이,퇴실시각,퇴실일자,환자생년월,성별코드,환자ID,입실기간
0,1219300234,2021-02-20,13:50:00,"ABGA coding (Des),Artery blood",342.0,NaN,NaN,2021-02-21,212123.0,81세,14:30:00,2021-03-02,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,2021-02-21,212123.0,81세,14:30:00,2021-03-02,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"ABGA interpretation (Des),Artery blood",NaN,NaN,NaN,2021-02-21,43234.0,81세,14:30:00,2021-03-02,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,2021-02-22,45628.0,81세,14:30:00,2021-03-02,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,2021-02-22,45628.0,81세,14:30:00,2021-03-02,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799995,1169043575,2020-05-19,18:00:00,"ABGA reading (Des),Artery blood",NaN,NaN,NaN,2020-05-20,155439.0,66세,17:10:00,2020-05-20,195307,F,11643575,1 days
799996,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,2020-05-20,155439.0,66세,17:10:00,2020-05-20,195307,F,11643575,1 days
799997,1169043575,2020-05-19,18:00:00,"Base excess (Qn),Artery blood",-1.8,NaN,NaN,2020-05-20,155439.0,66세,17:10:00,2020-05-20,195307,F,11643575,1 days
799998,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,29.0,23.0,2020-05-20,155439.0,66세,17:10:00,2020-05-20,195307,F,11643575,1 days
799999,1169043575,2020-05-19,18:00:00,"Potassium (Qn)[POCT],Blood",3.7,NaN,NaN,2020-05-20,155439.0,66세,17:10:00,2020-05-20,195307,F,11643575,1 days

In [27]:
trans1

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,접수일자,접수시각,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,80세,2021-02-21,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",47.0,45.0,35.0,80세,2021-02-21,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464314,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",92.5,108.0,83.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464315,1169043575,2020-05-19,18:00:00,"pCO2 (Qn)[EM],Artery blood",38.1,45.0,35.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464316,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464317,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464318,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,29.0,23.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days