In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
patient = pd.read_csv("patient_3.csv", encoding='cp949')

In [4]:
patient

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108,83,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100,94,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100,94,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",134.1,108,83,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",97.0,108,83,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,1219281863,2021-02-20,19:35:00,"pO2 (Qn)[EM],Artery blood",51.2,108,83,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
230,1219281863,2021-02-20,19:35:00,"pO2 (Qn)[EM],Artery blood",69.9,108,83,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
231,1219281863,2021-02-20,19:35:00,"pO2 (Qn)[EM],Artery blood",58.9,108,83,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
232,1219281863,2021-02-20,19:35:00,"O2 saturation (Qn),Artery blood",89.1,100,94,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
233,1219281863,2021-02-20,19:35:00,"O2 saturation (Qn),Artery blood",95.0,100,94,50대,2021-02-24,1:30:00,196311,F,12181863,4 days

In [5]:
trans1 = pd.read_csv("trans_1.csv", encoding='cp949')

In [6]:
trans2 = pd.read_csv("trans_2.csv", encoding='cp949')

In [7]:
trans1

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,접수일자,접수시각,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,80세,2021-02-21,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",47.0,45.0,35.0,80세,2021-02-21,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464314,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",92.5,108.0,83.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464315,1169043575,2020-05-19,18:00:00,"pCO2 (Qn)[EM],Artery blood",38.1,45.0,35.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464316,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464317,1169043575,2020-05-19,18:00:00,"Glucose (Qn)[POCT],Blood",299.0,99.0,70.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
464318,1169043575,2020-05-19,18:00:00,"Bicarbonate (Qn),Artery blood",22.9,29.0,23.0,60대,2020-05-20,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days

In [8]:
trans2

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,접수일자,접수시각,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",33.3,45.0,35.0,80세,2021-02-24,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",134.1,108.0,83.0,80세,2021-02-24,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",90.3,108.0,83.0,80세,2021-02-24,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",97.3,100.0,94.0,80세,2021-02-28,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",40.9,45.0,35.0,80세,2021-02-23,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188141,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-18,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
188142,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-18,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
188143,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-18,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
188144,1169043575,2020-05-19,18:00:00,"O2 saturation (Qn),Artery blood",98.4,100.0,94.0,60대,2020-05-18,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
188145,1169043575,2020-05-19,18:00:00,"O2 saturation (Qn),Artery blood",97.1,100.0,94.0,60대,2020-05-25,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days

In [9]:
trans = pd.concat([trans1, trans2], axis=0)

In [10]:
trans

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,접수일자,접수시각,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,80세,2021-02-21,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-02-22,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",47.0,45.0,35.0,80세,2021-02-21,NaN,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188141,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-18,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
188142,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-18,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
188143,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-18,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
188144,1169043575,2020-05-19,18:00:00,"O2 saturation (Qn),Artery blood",98.4,100.0,94.0,60대,2020-05-18,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days
188145,1169043575,2020-05-19,18:00:00,"O2 saturation (Qn),Artery blood",97.1,100.0,94.0,60대,2020-05-25,NaN,2020-05-20,17:10:00,195307,F,11643575,1 days

In [11]:
trans = trans.drop(['접수일자', '접수시각'], axis=1)

In [12]:
trans

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",47.0,45.0,35.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188141,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-20,17:10:00,195307,F,11643575,1 days
188142,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-20,17:10:00,195307,F,11643575,1 days
188143,1169043575,2020-05-19,18:00:00,"pO2 (Qn)[EM],Artery blood",27.5,108.0,83.0,60대,2020-05-20,17:10:00,195307,F,11643575,1 days
188144,1169043575,2020-05-19,18:00:00,"O2 saturation (Qn),Artery blood",98.4,100.0,94.0,60대,2020-05-20,17:10:00,195307,F,11643575,1 days
188145,1169043575,2020-05-19,18:00:00,"O2 saturation (Qn),Artery blood",97.1,100.0,94.0,60대,2020-05-20,17:10:00,195307,F,11643575,1 days

In [13]:
patient

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108,83,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100,94,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100,94,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",134.1,108,83,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",97.0,108,83,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,1219281863,2021-02-20,19:35:00,"pO2 (Qn)[EM],Artery blood",51.2,108,83,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
230,1219281863,2021-02-20,19:35:00,"pO2 (Qn)[EM],Artery blood",69.9,108,83,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
231,1219281863,2021-02-20,19:35:00,"pO2 (Qn)[EM],Artery blood",58.9,108,83,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
232,1219281863,2021-02-20,19:35:00,"O2 saturation (Qn),Artery blood",89.1,100,94,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
233,1219281863,2021-02-20,19:35:00,"O2 saturation (Qn),Artery blood",95.0,100,94,50대,2021-02-24,1:30:00,196311,F,12181863,4 days

In [18]:
trans_1 = trans[(trans["환자ID"] == 12100234)]

In [19]:
trans_1

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
0,1219300234,2021-02-20,13:50:00,"Bicarbonate (Qn),Artery blood",27.5,29.0,23.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
1,1219300234,2021-02-20,13:50:00,"pO2 (Qn)[EM],Artery blood",117.8,108.0,83.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
4,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",47.0,45.0,35.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",96.5,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
116,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",99.1,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
117,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",35.2,45.0,35.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
118,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",40.8,45.0,35.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
119,1219300234,2021-02-20,13:50:00,"pCO2 (Qn)[EM],Artery blood",40.3,45.0,35.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days

In [20]:
trans_2 = trans[(trans["환자ID"] == 12181863)]

In [21]:
trans_2

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
369,1219281863,2021-02-20,19:35:00,"Hct (Qn)[POCT],Blood",29.0,48.0,36.0,50대,2021-02-24,01:30:00,196311,F,12181863,4 days
370,1219281863,2021-02-20,19:35:00,"Hct (Qn)[POCT],Blood",24.0,48.0,36.0,50대,2021-02-24,01:30:00,196311,F,12181863,4 days
371,1219281863,2021-02-20,19:35:00,"Glucose (Qn)[POCT],Blood",72.0,99.0,70.0,50대,2021-02-24,01:30:00,196311,F,12181863,4 days
372,1219281863,2021-02-20,19:35:00,"Glucose (Qn)[POCT],Blood",316.0,99.0,70.0,50대,2021-02-24,01:30:00,196311,F,12181863,4 days
373,1219281863,2021-02-20,19:35:00,"Glucose (Qn)[POCT],Blood",216.0,99.0,70.0,50대,2021-02-24,01:30:00,196311,F,12181863,4 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1219281863,2021-02-20,19:35:00,"pCO2 (Qn)[EM],Artery blood",34.6,45.0,35.0,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
151,1219281863,2021-02-20,19:35:00,"pO2 (Qn)[EM],Artery blood",58.9,108.0,83.0,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
152,1219281863,2021-02-20,19:35:00,"O2 saturation (Qn),Artery blood",89.1,100.0,94.0,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
153,1219281863,2021-02-20,19:35:00,"pCO2 (Qn)[EM],Artery blood",31.9,45.0,35.0,50대,2021-02-24,1:30:00,196311,F,12181863,4 days
154,1219281863,2021-02-20,19:35:00,"O2 saturation (Qn),Artery blood",95.0,100.0,94.0,50대,2021-02-24,1:30:00,196311,F,12181863,4 days

In [22]:
trans = pd.concat([trans_1, trans_2], axis=0)

In [24]:
trans_3 = trans[(trans["검사코드NM"] == 'O2 saturation (Qn),Artery blood')]

In [25]:
trans_4 = trans[(trans["검사코드NM"] == 'pO2 (Qn)[EM],Artery blood')]

In [26]:
trans_5 = trans[(trans["검사코드NM"] == 'Sodium (Qn)[POCT],Blood')]

In [27]:
trans = pd.concat([trans_3, trans_4, trans_5], axis=0)

In [28]:
trans

,연구번호,입실일자,입실시각,검사코드NM,검사결과값(숫자),기준치상한값,기준치하한값,검사나이,퇴실일자,퇴실시각,환자생년월,성별코드,환자ID,입원기간
2,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
3,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
13,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",98.3,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
17,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",97.3,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
22,1219300234,2021-02-20,13:50:00,"O2 saturation (Qn),Artery blood",96.8,100.0,94.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1219300234,2021-02-20,13:50:00,"Sodium (Qn)[POCT],Blood",137.0,145.0,135.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
181,1219300234,2021-02-20,13:50:00,"Sodium (Qn)[POCT],Blood",137.0,145.0,135.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
328,1219300234,2021-02-20,13:50:00,"Sodium (Qn)[POCT],Blood",137.0,145.0,135.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
349,1219300234,2021-02-20,13:50:00,"Sodium (Qn)[POCT],Blood",137.0,145.0,135.0,80세,2021-03-02,14:30:00,193909,M,12100234,10 days
404,1219281863,2021-02-20,19:35:00,"Sodium (Qn)[POCT],Blood",136.0,145.0,135.0,50대,2021-02-24,01:30:00,196311,F,12181863,4 days